version: '3'

services:

  app:
    image: python:3.7.11-alpine3.13
    command: sh -c "python web/manage.py runserver"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/opt/webapp
    working_dir: /opt/webapp
    env_file:
      - .env
    network_mode: host
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    env_file:
      - .env
    volumes:
      - ./docker/postgres/data/dump.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz

